/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.SocketChannel;
import javax.swing.JOptionPane;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.util.EntityUtils;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.client.ResponseHandler;
/**
 *
 * @author pc-user
 */
public class RunChat extends javax.swing.JFrame {

   private final int MAXLEN = 1024;

   /**
    * Creates new form RunChat
    */
   public RunChat(SocketChannel socket) {
      initComponents();
      replyTxt.setText("");
      new LineReader(socket).start();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPopupMenu1 = new javax.swing.JPopupMenu();
      jDialog1 = new javax.swing.JDialog();
      jScrollPane1 = new javax.swing.JScrollPane();
      chatTxt = new javax.swing.JTextArea();
      sendTxt = new javax.swing.JTextField();
      listRoomsBtn = new javax.swing.JButton();
      logoutBtn = new javax.swing.JButton();
      listUsersBtn = new javax.swing.JButton();
      listUsersRoomLbl = new javax.swing.JLabel();
      roomListUsersTxt = new javax.swing.JTextField();
      roomChangeRoomTxt = new javax.swing.JTextField();
      changeRoomBtn = new javax.swing.JButton();
      changeRoomListLbl = new javax.swing.JLabel();
      logoutBtn1 = new javax.swing.JButton();
      replyTxt = new javax.swing.JLabel();
      jScrollPane3 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList();

      javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
      jDialog1.getContentPane().setLayout(jDialog1Layout);
      jDialog1Layout.setHorizontalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jDialog1Layout.setVerticalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      chatTxt.setEditable(false);
      chatTxt.setColumns(20);
      chatTxt.setRows(5);
      jScrollPane1.setViewportView(chatTxt);

      sendTxt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sendTxtActionPerformed(evt);
         }
      });

      listRoomsBtn.setText("List Rooms");
      listRoomsBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            listRoomsBtnActionPerformed(evt);
         }
      });

      logoutBtn.setText("Logout");
      logoutBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtnActionPerformed(evt);
         }
      });

      listUsersBtn.setText("List Users in Room");
      listUsersBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            listUsersBtnActionPerformed(evt);
         }
      });

      listUsersRoomLbl.setText("Room:");

      changeRoomBtn.setText("Change Room");
      changeRoomBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            changeRoomBtnActionPerformed(evt);
         }
      });

      changeRoomListLbl.setText("Room:");

      logoutBtn1.setText("Inbox");
      logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtn1ActionPerformed(evt);
         }
      });

      replyTxt.setForeground(new java.awt.Color(0, 102, 204));
      replyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      replyTxt.setText("Login ok");
      replyTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jList1.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane3.setViewportView(jList1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(sendTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
               .addComponent(jScrollPane1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(listRoomsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(listUsersRoomLbl)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(roomListUsersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(listUsersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(changeRoomListLbl)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(roomChangeRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(changeRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(replyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(logoutBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(listRoomsBtn)
                  .addGap(26, 26, 26)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(listUsersRoomLbl)
                     .addComponent(roomListUsersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(listUsersBtn)
                  .addGap(54, 54, 54)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(changeRoomListLbl)
                     .addComponent(roomChangeRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(changeRoomBtn)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(replyTxt)
                  .addGap(85, 85, 85)
                  .addComponent(logoutBtn1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(logoutBtn)
                  .addGap(26, 26, 26))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(sendTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(25, 25, 25))))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void sendTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTxtActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_sendTxtActionPerformed

   private void listRoomsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRoomsBtnActionPerformed
      CloseableHttpClient httpclient = HttpClients.createDefault();
      try {
         try {
            HttpGet httpget = new HttpGet("http://localhost:8080/rooms");

            System.out.println("Executing request " + httpget.getRequestLine());

            // Create a custom response handler
            ResponseHandler<String> responseHandler = (final HttpResponse response) -> {
               int status = response.getStatusLine().getStatusCode();
               String responseBody = null;
               if (status == 200) {
                  HttpEntity entity = response.getEntity();
                  responseBody = entity != null ? EntityUtils.toString(entity) : null;
               }
               return responseBody;
            };
            String responseBody = httpclient.execute(httpget, responseHandler);
            if(responseBody != null){
               System.out.println(responseBody);
            } else{
               errorBox("");
            }
         } finally {
            httpclient.close();
         }
      } catch (IOException ex) {
         errorBox(ex.getMessage());
      }
   }//GEN-LAST:event_listRoomsBtnActionPerformed

   private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_logoutBtnActionPerformed

   private void listUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsersBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_listUsersBtnActionPerformed

   private void changeRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRoomBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_changeRoomBtnActionPerformed

   private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_logoutBtn1ActionPerformed

   private class LineReader extends Thread {

      private final SocketChannel socket;
      private final ByteBuffer in = ByteBuffer.allocate(MAXLEN);
      private final ByteBuffer out = ByteBuffer.allocate(MAXLEN);

      public LineReader(SocketChannel socket) {
         this.socket = socket;
      }

      @Override
      public void run() {
         boolean eof = false;
         byte b = 0;
         try {
            for (;;) {
               if (socket.read(in) <= 0) {
                  eof = true;
               }
               in.flip();
               while (in.hasRemaining()) {
                  b = in.get();
                  out.put(b);
                  if (b == '\n') {
                     break;
                  }
               }
               if (eof || b == '\n') { // send line
                  out.flip();
                  if (out.remaining() > 0) {
                     byte[] ba = new byte[out.remaining()];
                     out.get(ba);
                     out.clear();
                     chatTxt.append(new String(ba));
                  }
               }
               if (eof && !in.hasRemaining()) {
                  break;
               }
               in.compact();
            }
            errorBox("");
         } catch (IOException e) {
            errorBox(e.getMessage());
         }
      }
   }

   private static void errorBox(String infoMessage) {
      JOptionPane.showMessageDialog(null, infoMessage, "Something Went Wrong", JOptionPane.ERROR_MESSAGE);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton changeRoomBtn;
   private javax.swing.JLabel changeRoomListLbl;
   private javax.swing.JTextArea chatTxt;
   private javax.swing.JDialog jDialog1;
   private javax.swing.JList jList1;
   private javax.swing.JPopupMenu jPopupMenu1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JButton listRoomsBtn;
   private javax.swing.JButton listUsersBtn;
   private javax.swing.JLabel listUsersRoomLbl;
   private javax.swing.JButton logoutBtn;
   private javax.swing.JButton logoutBtn1;
   private javax.swing.JLabel replyTxt;
   private javax.swing.JTextField roomChangeRoomTxt;
   private javax.swing.JTextField roomListUsersTxt;
   private javax.swing.JTextField sendTxt;
   // End of variables declaration//GEN-END:variables
}
