package chatserver.util;

public enum MsgType {

   DATA, COMMAND, EOF, IOE, ENTER, LEAVE, LINE,
   ROOM_INFO, CREATE_ROOM, DELETE_ROOM,
   OK, INVALID,
   CREATE, REMOVE, LOGIN, LOGIN_OK, LOGOUT,
   NEW_PRIVATE_MESSAGE, PRIVATE, INBOX, SHOW_INBOX,
   CHANGE_ROOM
}
