/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.SocketChannel;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-user
 */
public class RunChat extends javax.swing.JFrame {

   private final int MAXLEN = 1024;

   /**
    * Creates new form RunChat
    */
   public RunChat(SocketChannel socket) {
      initComponents();
      new LineReader(socket).start();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPopupMenu1 = new javax.swing.JPopupMenu();
      jDialog1 = new javax.swing.JDialog();
      jScrollPane1 = new javax.swing.JScrollPane();
      chatTxt = new javax.swing.JTextArea();
      sendTxt = new javax.swing.JTextField();
      listRoomsBtn = new javax.swing.JButton();
      logoutBtn = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      restTxt = new javax.swing.JTextArea();
      listUsersBtn = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      roomListUsersTxt = new javax.swing.JTextField();
      roomChangeRoomTxt = new javax.swing.JTextField();
      changeRoomBtn = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      logoutBtn1 = new javax.swing.JButton();

      javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
      jDialog1.getContentPane().setLayout(jDialog1Layout);
      jDialog1Layout.setHorizontalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jDialog1Layout.setVerticalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      chatTxt.setEditable(false);
      chatTxt.setColumns(20);
      chatTxt.setRows(5);
      jScrollPane1.setViewportView(chatTxt);

      sendTxt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sendTxtActionPerformed(evt);
         }
      });

      listRoomsBtn.setText("List Rooms");
      listRoomsBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            listRoomsBtnActionPerformed(evt);
         }
      });

      logoutBtn.setText("Logout");
      logoutBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtnActionPerformed(evt);
         }
      });

      restTxt.setEditable(false);
      restTxt.setColumns(20);
      restTxt.setRows(5);
      restTxt.setPreferredSize(new java.awt.Dimension(200, 75));
      jScrollPane2.setViewportView(restTxt);

      listUsersBtn.setText("List Users in Room");
      listUsersBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            listUsersBtnActionPerformed(evt);
         }
      });

      jLabel1.setText("Room:");

      changeRoomBtn.setText("Change Room");
      changeRoomBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            changeRoomBtnActionPerformed(evt);
         }
      });

      jLabel2.setText("Room:");

      logoutBtn1.setText("Inbox");
      logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtn1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(sendTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap())
               .addGroup(layout.createSequentialGroup()
                  .addGap(40, 40, 40)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(listRoomsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomListUsersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(listUsersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomChangeRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(changeRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(logoutBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(listRoomsBtn)
                  .addGap(26, 26, 26)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(roomListUsersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(listUsersBtn)
                  .addGap(29, 29, 29)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(roomChangeRoomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(changeRoomBtn)
                  .addGap(32, 32, 32)
                  .addComponent(logoutBtn1)
                  .addContainerGap(94, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(sendTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(logoutBtn))
                  .addGap(25, 25, 25))))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void sendTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTxtActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_sendTxtActionPerformed

   private void listRoomsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRoomsBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_listRoomsBtnActionPerformed

   private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_logoutBtnActionPerformed

   private void listUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsersBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_listUsersBtnActionPerformed

   private void changeRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRoomBtnActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_changeRoomBtnActionPerformed

   private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_logoutBtn1ActionPerformed

   private class LineReader extends Thread {

      private final SocketChannel socket;
      private final ByteBuffer in = ByteBuffer.allocate(MAXLEN);
      private final ByteBuffer out = ByteBuffer.allocate(MAXLEN);

      public LineReader(SocketChannel socket) {
         this.socket = socket;
      }

      @Override
      public void run() {
         boolean eof = false;
         byte b = 0;
         try {
            for (;;) {
               if (socket.read(in) <= 0) {
                  eof = true;
               }
               in.flip();
               while (in.hasRemaining()) {
                  b = in.get();
                  out.put(b);
                  if (b == '\n') {
                     break;
                  }
               }
               if (eof || b == '\n') { // send line
                  out.flip();
                  if (out.remaining() > 0) {
                     byte[] ba = new byte[out.remaining()];
                     out.get(ba);
                     out.clear();
                     chatTxt.append(new String(ba));
                  }
               }
               if (eof && !in.hasRemaining()) {
                  break;
               }
               in.compact();
            }
            errorBox("");
         } catch (IOException e) {
            errorBox(e.getMessage());
         }
      }
   }

   private static void errorBox(String infoMessage) {
      JOptionPane.showMessageDialog(null, infoMessage, "Something Went Wrong", JOptionPane.ERROR_MESSAGE);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton changeRoomBtn;
   private javax.swing.JTextArea chatTxt;
   private javax.swing.JDialog jDialog1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPopupMenu jPopupMenu1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JButton listRoomsBtn;
   private javax.swing.JButton listUsersBtn;
   private javax.swing.JButton logoutBtn;
   private javax.swing.JButton logoutBtn1;
   private javax.swing.JTextArea restTxt;
   private javax.swing.JTextField roomChangeRoomTxt;
   private javax.swing.JTextField roomListUsersTxt;
   private javax.swing.JTextField sendTxt;
   // End of variables declaration//GEN-END:variables
}
